### ISSUE TITLE
what duh heeeaaayyyeyll ooaahhh mahhh gaaaawwdd

### ISSUE THREAD

**Issue by James62-f** [SplashAni/RandomMeteor#6]
Leave a comment

hell     developer     of         randMeteo., i hav trying to use client for moth now and                  stil no worc???./? i c   an lode in meto clinte but clinte       mojules ar not      functon or trés yuseless      and coded like                           garbo xd this is serios ishoo tho plz fix this bugg thank.    
![Capture](https://github.com/SplashAni/RandomMeteor/assets/97754379/c600a729-1dda-492c-86d4-fb2f84ae505f)
![Capture2](https://github.com/SplashAni/RandomMeteor/assets/97754379/697903b3-6ee5-4f8f-8292-2019d54ca9f5)
![Capture](https://github.com/SplashAni/RandomMeteor/assets/97754379/c35f152e-cb46-40a7-82b6-cd323809005f)
![3](https://github.com/SplashAni/RandomMeteor/assets/97754379/28fd80c3-3513-487c-ad19-4542391ac6d2)

**Comment by anoncx** [comment]
bro it works fine u prob just got an extra Chromosom

**Comment by SplashAni** [comment]
nah wtf

**Comment by SplashAni** [comment]
ok ill fix soon moudly nice acc
