### ISSUE TITLE
good addon update to 1.20.2

### ISSUE THREAD

**Issue by Ancnymous** [SplashAni/RandomMeteor#7]
meteor has now updated to 1.20.2 so you should update it too if you update it a lot more peoples will use it

**Comment by SplashAni** [comment]
soon ™

**Comment by TherealONE12** [comment]
> soon ™

Pls also to 1.20.4

**Comment by pixo2000** [comment]
When soon? Need minecart aura in 1.20.2 pls

**Comment by SplashAni** [comment]
ok ill do it rn

**Comment by Anonimouze** [comment]
> ok ill do it rn

Update it to 1.20.4 if you do it please 1.20.2 is kinda outdated.

**Comment by Anonimouze** [comment]
> ok ill do it rn

DONT update to 1.20.2 update to 1.20.4

**Comment by pixo2000** [comment]
Why not both? Its easier to update to 1.20.2 and then to 1.20.4... think so

**Comment by Anonimouze** [comment]
> Why not both? Its easier to update to 1.20.2 and then to 1.20.4... think so

Sure but I think its too tough for him.

**Comment by Anonimouze** [comment]
> Why not both? Its easier to update to 1.20.2 and then to 1.20.4... think so

And also meteor and some other addons are on 1.20.4. So 1.20.2 is kinda outdated
